name: Gitleaks Scan

on: [push, pull_request]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run Gitleaks
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required for reporting

    - name: Run Trivy vulnerability scan
      uses: aquasecurity/trivy-action@master
      with:
          # Specify the target to scan (e.g., 'fs' for filesystem, 'image' for a container image)
        scan-type: 'fs'     